gui_title = ":books: FOIArchive"
favicon = "static/hl-logo-favicon.png"
search_str_help="""
Use double quotes for phrases, OR for logical or, and - for logical not.
"""
info_msg="""
Please help us improve FOIArchive search by completing our 
[survey](https://forms.gle/xoUQLQJVXDmqy2bU9).
"""
corpus_placeholder="""
Optionally restrict to specific corpora
"""
classification_placeholder="""
Optionally restrict to specific classifications
"""
classification_help="""
Some documents do not include original classification in metadata, so consider
including the 'unknown' classification when searching by classification.
"""
entity_placeholder="""
Optionally restrict to specific entities
"""
entity_help="""
Selecting values for this field restricts query results to documents 
referencing specific people, places, organizations, and other entities as 
identified by [named entity recognition (NER)](https://en.wikipedia.org/wiki/Named-entity_recognition). 
Checking the associated 'All entities appear in document' checkbox restricts 
query results to documents containing all selected entities  - unchecking 
limits query results to documents containing at least one selected entity.  

Entities are currently not available for the Cabinet or CPDOC
corpora. Therefore, selecting entity values excludes query results from these 
corpora. We are actively working to extend our coverage to additional corpora 
to enhance your search experience.

Like topic modeling, NER is a probabilistic process; its results don't rival 
those of a skilled human annotator. If you do not find an entity in the 
dropdown corresponding to the person, place, or organization you wish to 
search for, we suggest you enter the name into the full-text field."""
entity_warning="""
Specifying entities currently excludes results from the Cabinet and CPDOC corpora.
"""
date_help="""
Some documents do not include date metadata. You can expand your search
to include these documents by checking 'Include 
documents without a date'.
"""
help_action = "mailto:info@history-lab.org?subject=History Lab Help Request"
bug_action= "mailto:info@history-lab.org?subject=History Lab Bug Report"
about_body = """
Built by Columbia University's [History Lab](http://history-lab.org) with generous support 
from the NEH.
"""
corpora_description="static/corpora_description.md"
#
table_name = "foiarchive.docs"
max_rows = 2000     # results must be <= to display detail records
#
docviewer_url="https://foiarchive-docviewer.streamlit.app"
#
sidebar_footer="""
Need assistance or have feedback to share? Don't hesitate to 
[contact us](mailto:info@history-lab.org?subject=FOIArchive%20Search).
"""
# not used currently but should be
# schema =
# tsvector_col =